# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright 2026 Koray Taylan Davgana

FROM docker.io/library/debian@sha256:f324c7ff54321e8d9c588493a20244965938ce0aa50bbd1022d38010e9ffc4b1

RUN useradd -m -u 1000 client

USER client
