#!/usr/bin/env bun
// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright 2026 Koray Taylan Davgana

import { prepareWorkflowFixture } from "../src/preparation/workflow-fixture.ts";

const arguments_ = process.argv.slice(2);
if (arguments_.length !== 4) {
	console.error("usage: scripts/prepare_workflow_fixture AGENT_JAR AGENT_SHA256 PREPARED_MAVEN_CACHE DURABLE_DESTINATION");
	process.exit(2);
}
try {
	console.log(await prepareWorkflowFixture(arguments_[0]!, arguments_[1]!, arguments_[2]!, arguments_[3]!));
} catch (failure) {
	console.error(failure instanceof Error ? failure.message : String(failure));
	process.exit(1);
}
